# Generated by Django 5.1.1 on 2024-10-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_study', '0002_lesson_alter_course_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_study.course', verbose_name='курс'),
        ),
    ]
