# Generated by Django 4.2.7 on 2025-05-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_study', '0007_coursesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='app_study.course', verbose_name='курс'),
        ),
    ]
