# Generated by Django 4.2.7 on 2025-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_study', '0008_alter_coursesubscription_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена курса'),
        ),
    ]
