# Generated by Django 4.2.7 on 2025-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_study', '0009_lesson_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена курса'),
        ),
    ]
