# Generated by Django 4.2.7 on 2025-06-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_study', '0010_remove_lesson_price_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
